FROM amazon/aws-cli:latest

# Remove old docker client if it exists
RUN rm -f /usr/bin/docker || true

# Install deps
RUN dnf install -y tar curl jq && dnf clean all

# Install latest Docker CLI
ENV DOCKER_VERSION=27.2.0

RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_VERSION.tgz -o docker.tgz \
    && tar xzf docker.tgz \
    && mv docker/* /usr/local/bin/ \
    && rm -rf docker docker.tgz

# Verify
RUN which docker && docker --version && aws --version
